### ISSUE TITLE
Stuck at "loading application resources"

### ISSUE THREAD

**Issue by miniscruff** [Adamcake/Bolt#9] opened 2023-12-16 06:17 UTC
Heyo, I am running into an issue launching now but was able to get the bolt launcher to work for a while, but for whatever reason after I moved it stopped working. Not sure where I could get any more debug info but here is what I do have.

Stuck at around 20%ish on the "Loading application resources" part of launching. App is not responding at all, including close and settings button. Closing bolt and the terminal does not close the client at all, not sure if it should though. I have checked about every day with the updates but it does not seem to have resolved itself.

OS: Ubuntu 22.04
WM: i3wm
Game: Runescape 3
Output:
```
▶ flatpak run com.adamcake.Bolt
[1215/220114.821535:ERROR:zygote_host_impl_linux.cc(218)] Failed to get Widevine CDM folder for sandbox forwarding
[1215/220115.122967:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[1215/220115.277989:WARNING:chrome_browser_cloud_management_controller.cc(87)] Could not create policy manager as CBCM is not enabled.
[B] OnContextInitialized
[B] Browser::Window popup constructor, this=93988777187760
[B] OnWindowCreated 0 this=93988777187760
[B] OnAfterCreated for browser 1
[B] OnBrowserCreated this=93988777187760 1
[R] OnBrowserCreated for browser 1
[R] OnLoadEnd for browser 1
[1215/220115.721263:ERROR:ev_root_ca_metadata.cc(161)] Failed to decode OID: 0
[B] Successfully spawned game process with pid 90
Gtk-Message: 22:01:25.739: Failed to load module "atk-bridge"
```

Client output:
```
Messages:
Game launch status: 'OK'
Latest client is already installed
Save-credentials status: OK
Successfully added login for <my account>
```

**Comment by Adamcake** [comment] 2023-12-16 15:21
It's working for me, but I do know there to be an issue with GTK when certain environment variables are set on the host PC. The `Failed to load module "atk-bridge"` is the important part.

Can you please run this command and show me the output:
`env | grep -i [ag]tk`

**Comment by Adamcake** [comment] 2023-12-16 15:34
Oh and `echo $NO_AT_BRIDGE` as well.

**Comment by miniscruff** [comment] 2023-12-16 19:48
```
▶ env | grep -i '[ag]tk'
GTK_IM_MODULE=ibus
GTK_MODULES=gail:atk-bridge
```
and the NO_AT_BRIDGE is empty.

**Comment by miniscruff** [comment] 2023-12-16 20:12
I tried to disable the atk-bridge but even without the error it still fails at the same spot.
```
~                                                                                              
▶ export GTK_MODULES=gail

~
▶ flatpak run com.adamcake.Bolt
[1216/121104.267346:ERROR:zygote_host_impl_linux.cc(218)] Failed to get Widevine CDM folder for sandbox forwarding
[1216/121104.467406:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[1216/121104.532708:WARNING:chrome_browser_cloud_management_controller.cc(87)] Could not create policy manager as CBCM is not enabled.
[B] OnContextInitialized
[B] Browser::Window popup constructor, this=94371539708720
[B] OnWindowCreated 0 this=94371539708720
[B] OnAfterCreated for browser 1
[B] OnBrowserCreated this=94371539708720 1
[R] OnBrowserCreated for browser 1
[R] OnLoadEnd for browser 1
[1216/121104.760678:ERROR:ev_root_ca_metadata.cc(161)] Failed to decode OID: 0
[B] Successfully spawned game process with pid 91
[B] CanClose for window 0, this=94371539708720
[B] DoClose for browser 1
[B] OnBrowserClosing this=94371539708720
[B] CanClose for window 0, this=94371539708720
[B] OnWindowClosing 0 this=94371539708720
[B] OnBrowserDestroyed this=94371539708720
[B] OnBeforeClose for browser 1, remaining windows 0
```

**Comment by Adamcake** [comment] 2023-12-16 20:52
I can reproduce this same issue by running Bolt with `NO_AT_BRIDGE=1`, but if I run the game without using Bolt then this issue doesn't happen. Something is causing the game to crash, I'm not sure what at the moment, but it's clearly related to GTK2.

**Comment by miniscruff** [comment] 2023-12-16 20:57
hmm, that is good to know, maybe there is an easy way to reinstall gtk2 or something?

**Comment by Adamcake** [comment] 2023-12-16 21:18
In fact, it seems like running the game with a terminal at all is what's causing this issue right now, so nothing to do with env variables. It only works when launched the "normal" way, i.e. using the .desktop file in a DE.

That's really strange... Maybe it has some kind of a problem with stdin or stdout?

**Comment by miniscruff** [comment] 2023-12-16 21:53
Hmm, well I don't really have a desktop in i3 so I don't even know what .desktop files are, well like how they are structured or used. I launch bolt using `flatpak run com.adamcake.Bolt` from the terminal.

**Comment by Adamcake** [comment] 2023-12-16 22:03
Do you remember when exactly it stopped working? Was it after a certain version was released? ([release dates](https://github.com/Adamcake/Bolt/blob/master/CMakeLists.txt#L46-L51)) or was it when you changed OS or anything like that?

**Comment by Adamcake** [comment] 2023-12-16 22:23
Seems that the lock-up is caused by both the launcher process and the game process trying to read from stdin, probably waiting for communications from each other, and getting a SIGTTIN signal.

But it's impossible to know if that's normal behaviour, since this issue is only occurring when running in a terminal.

**Comment by miniscruff** [comment] 2023-12-16 22:33
hmm, is there an alternative method I can start maybe that can test this theory? 

Well, I moved on the 17th, so I stopped playing a little before that and then booted up and tried again maybe a week ago which looks to before the 0.5.0 release. I don't think I updated the first time I tried but there were updates I got when I did run flatpak update.

```
"<release version=\"0.5.0\" date=\"2023-12-11\"/>"
"<release version=\"0.4.0\" date=\"2023-11-03\"/>"
```

**Comment by Adamcake** [comment] 2023-12-17 00:09
Can you let me know if this works: `flatpak run com.adamcake.Bolt </dev/null`

This works for me, but either way I need to do some more investigation into what's going on here and what exactly has changed.

**Comment by miniscruff** [comment] 2023-12-17 01:22
> Can you let me know if this works: `flatpak run com.adamcake.Bolt </dev/null`
> 
> This works for me, but either way I need to do some more investigation into what's going on here and what exactly has changed.

This seems to work and I was able to launch the game this time. Not sure how much that helps you debug or if there is more I can test but let me know.

**Comment by Adamcake** [comment] 2023-12-17 01:41
Alright yeah I think that explains it then. I think GTK was just a red herring in this case, and there seems to have been an engine update in the last couple of weeks which has caused this issue and you're just the first to have noticed it.

I'll close this but please post here again if you have any more trouble getting in-game.

**Closed by Adamcake** 2023-12-17 01:41 UTC

**Comment by miniscruff** [comment] 2023-12-17 03:18
Awesome thanks for helping
