### ISSUE TITLE
Logged out from Bolt Launcher

### ISSUE THREAD

**Issue by OptimalSur** [Adamcake/Bolt#57] opened 2024-08-03 23:39 UTC
Hello, I'm not really sure if this is a bug or not, never had a really issue with bolt, but today when I launched bolt, it gave me a warning for me to accept saying that Jagex is not liable for any damages caused by bolt, which is strange since I've been using bolt for months, I closed it, saw a red warning I think it was something to do with communication, not really sure, and it logged me out, had to enter my details again.

Is this a normal behavior, the only think that I think it might have caused this was replacing my backup codes, but not really sure if that is the cause of the issue or not.

Thanks for reading and providing such a good launcher, and sorry if this isn't really an issue.

**Comment by Adamcake** [comment] 2024-08-04 00:19
The only reason that warning gets shown is if you don't have any login
sessions (even expired ones) when you open the launcher. There are a few
different reasons that could have happened:

- you accidentally logged out of your jagex account the previous time you
used the launcher
- your login session expired or was invalidated by something you did on the
website, and after that, you closed and re-opened the launcher before
logging back in
- the files in bolt's data directory were moved, modified, deleted, or the
location itself changed (i.e. XGD_DATA_HOME was changed)

You mentioned a red warning message - if you mean at the bottom of the
launcher window, then it very likely would have told you what the problem
was.

Probably not anything to worry about though.

**Comment by Adamcake** [comment] 2024-10-15 16:05
Closing as old. Nobody else has reported this - let me know if the issue is still persisting and I'll see if I can help debug.

**Closed by Adamcake** 2024-10-15 16:05 UTC
